export const GET_RECIPES = "GET_RECIPES";
export const GET_RECIPES_BY_NAME = "GET_RECIPES_BY_NAME";
export const ORDER_ALPHABETIC = "ORDER_ALPHABETIC";
export const ORDER_ORIGIN = "ORDER_ORIGIN";
export const FILTER_DIETS = "FILTER_DIETS";
export const GET_DETAIL = "GET_DETAIL";
